/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Ranking;

/**
 *
 * @author Raquel
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        silvio = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jogmanter = new javax.swing.JMenuItem();
        joglistar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        pegmanter = new javax.swing.JMenuItem();
        peglistar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aluno\\Desktop\\maxresdefault.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        silvio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/silvio (1).jpg"))); // NOI18N
        silvio.setText("jLabel2");
        silvio.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 153, 153)));
        silvio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                silvioMouseClicked(evt);
            }
        });

        jMenu1.setText("Jogador");

        jogmanter.setText("Jogador Manter");
        jogmanter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogmanterActionPerformed(evt);
            }
        });
        jMenu1.add(jogmanter);

        joglistar.setText("JOgador Listar");
        joglistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joglistarActionPerformed(evt);
            }
        });
        jMenu1.add(joglistar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pergunta");

        pegmanter.setText("Pergunta Manter");
        pegmanter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pegmanterActionPerformed(evt);
            }
        });
        jMenu2.add(pegmanter);

        peglistar.setText("Pergunta Listar");
        peglistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peglistarActionPerformed(evt);
            }
        });
        jMenu2.add(peglistar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ranking");

        jMenuItem5.setText("Lista Ranking");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(silvio, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(silvio)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jogmanterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogmanterActionPerformed
        // TODO add your handling code here:
        JogadorManter jog = new JogadorManter();
        jog.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jog.setVisible(true);
    }//GEN-LAST:event_jogmanterActionPerformed

    private void joglistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joglistarActionPerformed
        // TODO add your handling code here:
        JogadorListar jog = new JogadorListar();
        jog.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jog.setVisible(true);
    }//GEN-LAST:event_joglistarActionPerformed

    private void pegmanterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pegmanterActionPerformed
        // TODO add your handling code here:
        PerguntaManter peg = new PerguntaManter();
        peg.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        peg.setVisible(true);
    }//GEN-LAST:event_pegmanterActionPerformed

    private void peglistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peglistarActionPerformed
        // TODO add your handling code here:
        PerguntaListar peg = new PerguntaListar();
        peg.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        peg.setVisible(true);
    }//GEN-LAST:event_peglistarActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        RankingListar ran = null;
        try {
            ran = new RankingListar();
        } catch (ParseException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        ran.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        ran.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void silvioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_silvioMouseClicked
        // TODO add your handling code here:
        silvio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desktop/silvio(1).jpeg")));
    }//GEN-LAST:event_silvioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem joglistar;
    private javax.swing.JMenuItem jogmanter;
    private javax.swing.JMenuItem peglistar;
    private javax.swing.JMenuItem pegmanter;
    private javax.swing.JLabel silvio;
    // End of variables declaration//GEN-END:variables
}
